### ISSUE TITLE
Sessions not persisting/working when deploying on Heroku with multiple dynos

### ISSUE THREAD

**Issue by arunkappcino** [timtamimi/node.js-passport.js-template#1]
Hi,

I used this repository and found it's not working when we deployed it on heroku and used multiple dynos.

Can you please check and get back to me.

NOTE: using postgresQL
Thanks in advance.

**Comment by timtamimi** [comment]
Hi there,

I've just re-deployed this to a Heroku instance using Heroku Postgres and it seems to work fine for me.

Can you clarify what the error/issue is please? You may want to check your Heroku instance logs for hints. 

_For clarity, you do have to go into the DB and create a table called "users" in the public schema. You then have to create the following columns for the queries to work: firstName, lastName, email, password._

**Comment by arunkappcino** [comment]
Hi Tim,

Thanks for your quick response, did you tried it with multiple dynos like more than 2 dynos.

Right now I'm using 4 dynos and when I try to log in, it's logged me in successfully but when I refresh the page or try to go on another page it redirects me on the login page. because req.isAuthenticated() returns false.

**Comment by timtamimi** [comment]
Ah. The issue you're experiencing is to do with the cookie not persisting across the instances of your applications. This is a discrepancy between the way the `express-session` module works and the way Heroku dynos are designed to work.

I would suggest cloning or forking the repo, then uninstalling express-session and using `cookie-session` instead.

```
npm uninstall express-session
npm install cookie-session
```

You will then need change app.js from:
`var session = require("express-session");`
to
`var session = require("cookie-session");`


and then change
`app.use(session({secret: 'keyboard cat'}))`
to 
`app.use(session({ name: 'some session name', keys: ['keyboard cat']}))`

You can find more info on this StackOverflow question: https://stackoverflow.com/questions/17308935/setting-up-sessions-on-express-app-on-multiple-dynos-heroku-app

**Comment by arunkappcino** [comment]
Hello Tim,

Thank you so much, it's working now.

I really appreciate your quick help.
