### ISSUE TITLE
Unhandled promise rejections Error

### ISSUE THREAD

**Issue by JamesHere** [timtamimi/node.js-passport.js-template#2]
Hi, so I just try to deploy on my Heroku to see how it works.
But it got no response after I click login or create account.

The Heroku logs gave me this message "DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejection that are not handled will terminate the Node.js process with a non-zero exit code"

Do you know how to solve this problem? Many thanks!

**Comment by timtamimi** [comment]
Hi there. This warning normally relates to a missing `catch`.

Does it tell you which file/line the error relates to in the logs?

**Comment by JamesHere** [comment]
> Hi there. This warning normally relates to a missing `catch`.
> 
> Does it tell you which file/line the error relates to in the logs?

Hi, so what I did just clone the repo and push to the Heroku master. The DEMO will freeze if you want to login/register. And then it gave me the unhandled promise rejection error. Also "UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: connect ECONNREFUSED 127.0.0.1:5432"  It didn't tell me which file.

I though it just failed to connect to the database.

I noticed I may need to add my db connection details. So I found /lib/routes.js has "//const connectionString = process.env.DATABASE_URL;" I then just replaced the process.env.DATABASE_URL with my Heroku Postgres Database URL. But it still doesn't work.

I think I did it in the wrong way... Is there anything I need to add to the current code on the repo to make it connect to my database?

Thanks for the reply!

**Comment by timtamimi** [comment]
Hi there,

Yup. Sounds like your application is failing to connect to your database.

You are going along the right lines by attempting to place your database details into the `routes.js` file. 

Direct your attention to lines 24-31 instead of line 20.

```

const pool = new Pool({
	user: process.env.PGUSER,
	host: process.env.PGHOST,
	database: process.env.PGDATABASE,
	password: process.env.PGPASSWORD,
	port: process.env.PGPORT,
	ssl: true
});
```

The applications wants these details. Each variable prefixed with `process.env.SOMETHING` should be coming from your environment variables. 

In Heroku, the easiest way to add/manage environment variables is through the app dashboard. Go to the app, then go to the "Settings" tab, and you will be presented with a "Config" section as seen below

![image](https://user-images.githubusercontent.com/6029895/79631885-d3913900-8153-11ea-9197-9b96c0169125.png)


Edit this so that it looks similar to what I've got below:

![image](https://user-images.githubusercontent.com/6029895/79631914-f7ed1580-8153-11ea-96d3-2a183a930cc8.png)


Then re-run your application. 

Good luck out there!

**Comment by JamesHere** [comment]
Thank you so much!

**Comment by JamesHere** [comment]
> Hi there,
> 
> Yup. Sounds like your application is failing to connect to your database.
> 
> You are going along the right lines by attempting to place your database details into the `routes.js` file.
> 
> Direct your attention to lines 24-31 instead of line 20.
> 
> ```
> 
> const pool = new Pool({
> 	user: process.env.PGUSER,
> 	host: process.env.PGHOST,
> 	database: process.env.PGDATABASE,
> 	password: process.env.PGPASSWORD,
> 	port: process.env.PGPORT,
> 	ssl: true
> });
> ```
> 
> The applications wants these details. Each variable prefixed with `process.env.SOMETHING` should be coming from your environment variables.
> 
> In Heroku, the easiest way to add/manage environment variables is through the app dashboard. Go to the app, then go to the "Settings" tab, and you will be presented with a "Config" section as seen below
> 
> ![image](https://user-images.githubusercontent.com/6029895/79631885-d3913900-8153-11ea-9197-9b96c0169125.png)
> 
> Edit this so that it looks similar to what I've got below:
> 
> ![image](https://user-images.githubusercontent.com/6029895/79631914-f7ed1580-8153-11ea-96d3-2a183a930cc8.png)
> 
> Then re-run your application.
> 
> Good luck out there!

Hi, so I actually have some new problems. The app crash when I try to register a user. It seems like something was wrong with routes.js line 54
Error Logs:
 `/app/lib/routes.js:54
2020-04-19T03:47:40.213925+00:00 app[web.1]: if(result.rows[0]){
2020-04-19T03:47:40.213926+00:00 app[web.1]: ^
2020-04-19T03:47:40.213926+00:00 app[web.1]: 
2020-04-19T03:47:40.213927+00:00 app[web.1]: TypeError: Cannot read property 'rows' of undefined
`
Also,
If I try to log in, the webpage will show "Internal Server Error" and didn't return error. 

I am very new to Postgres but I think I need to manually create a table before running the app since
I didn't find the CREATE TABLE in the code. 

Am I on the right way? Thank you so much for the help!

**Comment by timtamimi** [comment]
@JamesHere Hi there. You do need to initialise the database. This is explained in [the tutorial](https://medium.com/@timtamimi/getting-started-with-authentication-in-node-js-with-passport-and-postgresql-2219664b568c).
